### ISSUE TITLE
Add DataTables API

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#1]
## Context
Now that we have a list of Products displayed in a regular HTML table, I want to add advanced interaction and control to the table.

**Notes:** We need to make sure to display the same columns, and also to modify the code so that the "edit" and "delete" buttons are part of the new data table.

## Tasks
- [ ] Add the CSS and and JS includes to the `Views/Shared/_Layout.chtml` file.
- [ ] Modify the `Areas/Admin/Views/Product/Index.chtml` file to initialize the normal table as a DataTable.
- [ ] Add a `wwwroot/js/product.js` with the Ajax script to add the data table.
- [ ] Add the edit and delete buttons in the `product.js` file.
- [ ] Add SweetAlert2 to notify the user of product deletion successful.

## Resources
* [DataTables Website](https://datatables.net/)
* [SweetAlert2](https://sweetalert2.github.io/)
* [Udemy Course: NET Core MVC - The Complete Guide 2023 \[E-commerce\]](https://www.udemy.com/course/complete-aspnet-core-21-course/) (lesson 101)

**Comment by MarissaCampa** [comment]
## Update

Added some screenshots of the progress.

### Product Index with enhanced data table (controls options for ordering by, filtering, etc)
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/5ecb71a8-e3bd-46ec-adf0-9b4ae2db4624)

### After clicking an object shows SweetAlert2 confirmation message
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/3d562742-4cea-45b5-a23c-198597bdc822)

### After deleting, reloading the datatable, and shows the toastr notification of "delete success"
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/f64d37d6-d3c2-48a5-be73-47fd25520a2f)
