### ISSUE TITLE
Add Shopping Cart to Project

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#10]
## Context 
I want to add capabilities for a shopping cart

## Tasks
- [x] Add Shopping Cart Model
- [x] Add Shopping Cart to Repository
- [x] Add ApplicationUser Repository
- [x] What will be Model for Details Page?
- [x] Add to Cart
- [x] Fix Issue with Add to Cart
- [x] A Weird Bug
- [x] Shopping Cart UI
- [x] Get Shopping Cart
- [x] Get Order Total in Shopping Cart
- [x] Dynamic Shopping Cart
- [x] Update Quantity in Shopping Cart
- [x] Order Summary UI

**Comment by MarissaCampa** [comment]
## Updated Screenshots

### The Button "Add to Cart" in the Product Details page now adds a new ShoppingCart Item to the ShoppingCartList (or increments by "count" if it already exists.

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b2f03b5e-c9bf-434d-ad18-6607064ca727)

### Shopping Cart Details, the Plus, Minus and Remove buttons increment, decrement or remove an item from the ShoppinCart List

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b5075588-bcd8-4961-8361-569bfe73e346)

### The Summary buttons returns the Summary View, which is just html template at this point

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/190add5f-2e31-4d3f-854a-5d04084a09e2)
