### ISSUE TITLE
Order Confirmation

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#12]
## Context
After adding Shopping Cart capabilities to my project, I need to be able to create an order, place it and confirm payment.

## Tasks
- [x] Create Order Header and Details Model
- [x] Add Order Header and Detail Repository
- [x] Make ShoppingCartVM more Dynamic
- [x] Summary GET Action Method
- [x] Load Summary UI with Data
- [x] Order Status
- [x] Summary POST Action
- [x] Place Order for Company Accounts
- [x] Register for Stripe Account
- [x] Configure Stripe in Project
- [x] Add Helper Methods in Order Header Repository
- [x] Stripe in Action
- [x] Confirm Stripe Payment
- [x] Order Placed Successfully with Stripe

## Resources
* [Udemy Course: NET Core MVC - The Complete Guide 2023 \[E-commerce\]](https://www.udemy.com/course/complete-aspnet-core-21-course/) (Section 11)

**Comment by MarissaCampa** [comment]
## Screenshots

### After shopping around, and adding items to the shopping cart, and click "Summary", it takes you to the summary page. Click on the Place Order button.

![Image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/398ab381-9ed9-4a68-a7ea-b984d7580770)

### It takes you to a Stripe Payment window, in test mode. Input a test credit card from Stripe and click "Pay"

![Image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/1c158fe8-000e-4213-95ba-e80f2a97589e)

### It redirects to the OrderConfirmation view and populates the information

![Image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/6a24da50-019f-4fed-adc1-4fb7852eeac6)

### It updates the OrderHeader table to reflect "Approved" in the OrderStatus and the PaymentStatus

![Image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/e56bac90-6684-4424-8df8-00d17e5d589b)
