### ISSUE TITLE
Order Management

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#15]
## Goal 
Add order management capabilities to the project.

## Tasks
- [x] OrderVM and Order Controller
- [x] Order List UI
- [x] Add Status Filter
- [x] Make Status Selected Active
- [x] Demo - Filters in Order List
- [x] Order Details Get Action
- [x] Loading Order Details Header
- [x] Display Order Details
- [x] Update Order Details
- [x] Only Admin and Employee Can See all Orders
- [x] Order Processing Buttons Logic
- [x] Ship Order
- [x] Cancel Order
- [x] Process Delayed Payment

**Comment by MarissaCampa** [comment]
# Updated Screenshots

### Navigation button to manage orders

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/8ce1e982-6462-4d0c-b0fe-6b4faabaaadc)

### Users can only see their own orders

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/ca985f64-66d2-444a-bd4c-2a719127a387)

### Admin and employees can see all orders

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/766459b4-5bc7-4b9f-8a16-2f4410b04e49)

### Order Details 

An order for a company user doesn't need to be paid off immediate, it is approved for delayed payment.

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/57580b6f-8f42-496b-9c17-f0307c31b078)

### admin or employees can see the button "Start Processing"

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/5d876926-65fc-4a54-800f-0a6cb8694c26)

### Changes the status of the order to "Processing", now it can be shipped 

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/ebd65e73-da41-409c-bd1d-8a915a4a8aee)

### After clicking the button "Ship Order"
If the carrier or the tracking number is empty, it will show a sweetalert notification

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b4037c72-917f-4e93-9648-2cd597be5221)

### Order was shipped successfully

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/bd15e3fd-36b9-4532-95f0-7b8d781d5bde)

### Company user can see the "Pay Now" button

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/7f05bb61-ab6f-4dae-91ce-61e4f647a129)

### Takes it to stripe payment page

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/fb6e1a96-97cc-42f4-8276-1b9f4c4d2f65)

### Payment successful

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/103e919a-4908-4349-9398-bf355626f6da)

### Order "Payment Status" changes to "Approved"

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/d8c5f9dd-59c6-4faa-92d1-934d38f42a2a)
