### ISSUE TITLE
Section 13: Advanced Concepts

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#17]
## Context

Section 13 of the course. Seeing advanced concepts

## Tasks

- [x] Authorization
- [x] Session in .NET Core
- [x] Remove from Session and Bug
- [x] Bug Solution and Logout
- [x] Create View Component
- [x] View Component in Action
- [x] Facebook Social Login
- [x] Facebook Login in Action
- [x] Creating Admin and Employee Accounts
- [x] Session Bug

**Comment by MarissaCampa** [comment]
# Screenshots

### Empty shopping cart when not logged in 

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/43936709-29f6-41fa-bcaf-d0b86dd57efb)

### It populates the shopping cart count when logged in

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/bb148098-7f38-4742-877d-54ae21ed1be0)

### When removing a product from the cart, it reduces the cart count

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/32b73d13-0e8f-4cbf-92e5-39d6991bb82c)

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/155df3b5-d8d4-4c41-888b-d3d08b3ef737)
