### ISSUE TITLE
Deployment & Email

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#19]
# Context
Section 14: Deployment & Email

# Tasks
- [x] DBInitializer Implementation
- [ ] SendGrid Email Setup
- [ ] Create Azure SQL Server and Database
- [ ] Downgrade to Net 7
- [ ] Azure Production Deployment
- [ ] Facebook Url
- [ ] Facebook Url Error
