### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#33]
# Context
Activities of the "Section 15: User Management" of the Udemy Course.

# Tasks
- [x] Add UserController with Index View to show all users in a smart table. 
- [x] Create a user.js file to use a UserController GetAll API call.
- [x] Add a Role property to the ApplicationUser model, and add a section to retrieve the role names for each user in the GetAll API in the UserController.
- [x] Add functionality for Lock/Unlocking Users, with toastr notifications for success.
- [x] Add admin capability for when you load all users, and click on Permissions, you can update the role, and if it's changed to Company, it displays the drop-down menu with the available companies. Update the role changes in the database.

**Comment by MarissaCampa** [comment]
# Screenshots 

## Manage User navigation menu

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/921ccf27-a553-4a6f-b36e-f7598823c8b1)

## Users List

### Locked
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/61c9d585-54d1-4a99-9b52-dc8cd26f054e)

### UnLocked
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/1d78a89e-0562-46c0-8df9-aa687e679f19)

## RoleManagement View 
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/2d2ef618-6b52-49d1-8e77-ff63122509f2)

If you switch the role to "Company", it will show the drop-down menu with the Company List

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/1c0631e3-05e4-4382-85eb-44265fde4492)

## Updated Role

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b18938d8-5c16-427f-a81c-f2f541d25f0b)
