### ISSUE TITLE
Multiple Product Image

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#37]
# Context
Contents of "Section 16: Multiple Product Image" of the Udemy course.

# Tasks
- [x] Remove ImageUrl from Product
- [x] Product Image Table 
- [x] Add Product Image Repository 
- [x] Upload Images on Product Upsert ]
- [x] Display Image on Update Product Page
- [x] Delete Image
- [x] Delete Product
- [x] Display Image in Shopping Cart
- [x] Add Bootstrap Carousel

**Comment by MarissaCampa** [comment]
# Screenshots 

#### Manage Product
Multiple images display when editing a Product. Also has the option to delete individual photos.

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/656b4c60-0c4b-4ec6-9061-f9d0f7f574c9)


#### Shopping cart shows the first product image for each product

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/7c221beb-0ef1-4065-aa0f-7b7cc7fd89b8)


#### Bootstrap carousel for product images in the Home/Details page

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/f7f30365-9a00-4a39-a870-72de5a8bd7dc)

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/c55ac34d-2b2b-4160-ad37-f7d82e67849a)
