### ISSUE TITLE
Add Product list to Home Page

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#4]
## Context
I need to add the available product list to the Home Screen, displayed in an elegant and attractive way for the customer.

## Tasks
- [x] Modify the Home Controller to include a unitOfWork instance to be able to get the product list through dependency injection.
- [x] Modify the `Customer/Views/Home/Index.chtml` file to display elegant cards that contain the products based out of a Product list.
- [x] Add a "Details" view for a specific Product Id that displays img, title, author, description (html code from rich text editor) and prices. 

## Resources
* [Udemy Course: NET Core MVC - The Complete Guide 2023 \[E-commerce\]](https://www.udemy.com/course/complete-aspnet-core-21-course/) (lesson 107, 108, 109)

**Comment by MarissaCampa** [comment]
## Update

### Home Page displaying available Products
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/7c298c3d-06bb-4299-bfce-155436c164a9)


### Details Page for a specific product id
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/3330a549-b6cb-4ec3-ac0e-279214475366)
