### ISSUE TITLE
Company CRUD

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#8]
## Context
One type of user of the website can be a Company, and a company has the option to process a payment until after 30 days after the order was placed. We need to create a model and database table for Company and perform CRUD operations.

## Tasks
- [x] Create Company Model/Table (Id[Key], Name[Required], StreetAddress, City, State, PostalCode, PhoneNumber
- [x] Add Company to Repository and UnitOfWork
- [x] Perform CRUD Operations on Company (using DataTables)
- [x] Dispay Company drop-down in the Register page
- [x] Toggle the Company drop-down if the UserRole drop-down is selected for "Company".
- [x] Register Company User

## Resources
[.NET Core MVC - The Complete Guide 2023](https://www.udemy.com/course/complete-aspnet-core-21-course)

**Comment by MarissaCampa** [comment]
## Updated Screenshots

### Added Company to the NavBar only for "Admin" users

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/48aca6da-c35e-4e6c-bbe8-ac3f8dc897fa)

### Added Company Index View

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/5211b678-c673-4b07-9a9b-fc55e984d91f)

### Upsert view, with option to either Update an existing Company, or Create a new one

#### Update existing Company

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/4c43a634-0265-497d-a9b7-78720a0fe7bd)

#### Create new Company

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/1c545a38-758d-4d5b-8cf8-12be7d8d078e)

### SweetAlert2 for Delete Company

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b2dd506d-5aef-4c72-b7b8-425bc285a124)

### Toggle "Company" drop-down in Register View, when User Role "Company" is selected

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/69afc6e8-5247-4b99-a4ca-357bfd2ecdf8)

#### Company drop-down becomes visible

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/b43fcbc8-0caf-4616-bc48-fe764ab84081)

#### Shows available companies to link the user to
![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/3d2a2814-1230-4926-a57a-88e275cb6fe5)
